# Generated by Django 2.1.7 on 2021-04-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='release_date',
            new_name='publish_date',
        ),
    ]
