# Generated by Django 3.1.7 on 2021-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='ndele.jpeg', null=True, upload_to='gallery/'),
        ),
    ]
