# Generated by Django 3.1.7 on 2021-04-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='project',
        ),
    ]
