# Generated by Django 3.1.7 on 2021-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210406_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='design_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
