# Generated by Django 3.1.7 on 2021-04-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210406_2153'),
        ('main', '0009_auto_20210407_1235'),
    ]

    operations = [
    ]
